version: "2"

services:
  neo4j:
    image: neo4j:4.3
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - kinesis2neo4j:/data

volumes:
  kinesis2neo4j: